### ISSUE TITLE
JOSS review on software paper

### ISSUE THREAD

**Issue by dominiquesydow** [project-gemmi/gemmi#201]
Hi @wojdyr,

I just read through the manuscript - it is well-written and has a clear and concise summary, very much appreciated. 

I have a few comments on the "Statement of need" section, referring to this paper version: https://github.com/openjournals/joss-reviews/issues/4200#issuecomment-1049297149

- [x] Could you please elaborate a bit more on the gap that GEMMI is filling? 
  - Examples of overlaps and trade-offs are nicely stated - which choices were made for GEMMI and why?
  - Are there examples of functionalities that the other packages do _not_ have?
- [x] If applicable (going hand-in-hand with the previous point), could you state in which cases a user might want to use GEMMI vs. CCTBX vs. Clipper? As someone who has not used any of these software packages, that would be my first question to deciding on which software to spend my time on.
- [x] Does it make sense to mention coot alongside software that has (at least a subset of similar) functionalities?
- [x] UglyMol is mentioned in the "Summary" as an application that uses GEMMI if I understand correctly.  Would make sense to add it also the list at the end of the "Statement of need" alongside autoBUSTER etc.?
- [x] References: If applicable, could you please add DOIs where missing?

Link to the review: https://github.com/openjournals/joss-reviews/issues/4200

**Comment by dominiquesydow** [comment]
Adding to the list above, at the moment the paper describes GEMMI nicely as a toolbox for working with crystallographic data. I think it would be beneficial to add a paragraph that shows examples of how this toolbox could be put together for example use cases (e.g. common tasks in a crystallographer's work life). 

This goes very much in hand with what I felt was missing when I went through the documentation and described in this issue: https://github.com/project-gemmi/gemmi/issues/202

**Comment by wojdyr** [comment]
Hi @dominiquesydow

thanks for taking the time to review this paper.

>     * [ ]  Could you please elaborate a bit more on the gap that GEMMI is filling?
>       
>       * Examples of overlaps and trade-offs are nicely stated - which choices were made for GEMMI and why?
>       * Are there examples of functionalities that the other packages do _not_ have?

There are many smaller and larger differences, but I couldn't find a representative example that would do justice to all the compared packages. Cctbx has order of magnitude more man-years of development and it doesn't have major gaps, but for sure there are small features in gemmi and clipper that are not in cctbx.

>     * [ ]  If applicable (going hand-in-hand with the previous point), could you state in which cases a user might want to use GEMMI vs. CCTBX vs. Clipper? As someone who has not used any of these software packages, that would be my first question to deciding on which software to spend my time on.

There is no easy answer to this. If the user needs only a small subset of functionality (say, reading a CIF file) they could compare how it can be in different packages, as well as how easy it's to find documentation and install different libraries.
Heavy users will often need custom features or changes in existing features. So they will need to frequently communicate with the project they use. And because they often work in a group doing method development for crystallography, and this groups is usually invested in one of the libraries, they go with what their colleagues use.
 
>     * [ ]  Does it make sense to mention coot alongside software that has (at least a subset of similar) functionalities?

Coot is using Clipper for most of the similar functionalities. (Coot development started in York, where Clipper is being developed). But thinking about it, I should mention MMDB (another library used by Coot).

>     * [ ]  UglyMol is mentioned in the "Summary" as an application that uses GEMMI if I understand correctly.  Would make sense to add it also the list at the end of the "Statement of need" alongside autoBUSTER etc.?

The list of projects is the Statement of need is far from complete. Github show that [58 repositories][1] depend on gemmi, so I didn't try to list all of them.

>     * [ ]  References: If applicable, could you please add DOIs where missing?

Yes, I'll update the paper soon.

I'll think about examples that could be added. This would need to be a new section in the paper.

Thanks for the review.

[1]: https://github.com/project-gemmi/gemmi/network/dependents?dependent_type=REPOSITORY&package_id=UGFja2FnZS01MjE0Nzg3MA%3D%3D

**Comment by wojdyr** [comment]
Thanks for thoughtful reading the paper. Comparison with other packages is a sensitive thing and it would be difficult to make for me, because I'm obviously biased. I'll rather wait for someone else to write it. But I understand such comparisons are useful. Recently I was trying to make sense of the landscape in molecular dynamics packages, but I haven't found any comparisons in documentations of these packages.

I added DOIs to all references (that have DOIs) and updated the paper.
