### ISSUE TITLE
Real space asymmetric unit implementation?

### ISSUE THREAD

**Issue by minhuanli** [project-gemmi/gemmi#216]
Hi, recently we would like to do some voxel parameterization in real space. It seems over-parameterized if we assign values independently to the whole unit cell. So a feature to generate a real space ASU given space group is useful.

Seems like gemmi is the best place for that feature to live. It says TODO in the gemmi documentation (https://gemmi.readthedocs.io/en/latest/symmetry.html#real-space). So we are wondering if that is on your plan now? Or anything we could to to help that part development? 

Also, cc to @kmdalton

**Comment by wojdyr** [comment]
I don't understand the voxel parametrization part, so I don't know exactly what you need, but indeed, ASU has been considered.

First, if you use grid and don't need contiguous asu, this can help:
https://gemmi.readthedocs.io/en/latest/grid.html#asu-and-maskedgrid

For contiguous asu, syminfo.lib in CCP4 has three different definitions, for example for P 21 21 21 it is:

    mapasu ccp4 0<=x<1; 0<=y<1; 0<=z<=1/4
    mapasu zero 0<=x<1; 0<=y<=1/4; 0<=z<1
    mapasu nonz 0<=x<1; 0<=y<=1/4; 0<=z<1

I see cctbx developers also did substantial research on the asu definitions:
http://cci.lbl.gov/asu_gallery/
(and interesting discussions in this thread: http://phenix-online.org/pipermail/cctbxbb/2007-June/000087.html)

In gemmi it'd be useful to have direct-space asu definitions when writing ccp4 maps, so that the map covers only the asu (that's how clipper and programs that use clipper, such as coot, write maps).

How would you like to use it for your project?

**Comment by minhuanli** [comment]
Thank you Marcin. All comments are helpful.
 
Let me first make some clarifications about the "voxel parameterization". It basically means we want to parameterize the intensity value of voxels in the real space unit cell grid. But it would be great if we can only independently parameterize a subset of the whole grid, which is the asu. Then using the symmetry operations to do mapping to the contiguous ones.

So ideally we hope to have an interface which takes a whole unit cell grid plus a space group, and outputs the index of voxels in the grid belonging to the asu.

About the `masked_asu` method you mentioned, is it working with reciprocal space or real space? If it works in real space, think that should already solve our problem.

And about the asu definitions you referred above, we have looked similar things before. The issue is that we still need a bridging function to fill the gap between the vertices and faces representations of asu and the grid representation of the unit cell, which would involve some interpolation and rounding operations. And looks like gemmi is a good place to have a well-defined approach to do that things (or maybe you have already done it).

Maybe more comments from kevin @kmdalton

**Comment by wojdyr** [comment]
masked_asu is for real space, but it's non-contiguous, so it won't be appropriate. It uses a simple method to mark asu:
it iterates through all the points (in any order) and
if a point is not assigned yet, it's marked as asu, and all its symmetry images are marked as non-asu

Last week I was comparing reciprocal asu definitions (CCP4 vs TNT), so it's a good time to look also into direct space asu.
From what I see the CCP4 library stores only x, y and z limits in syminfo.lib. This is suitable to determine the necessary coverage of the map file, but it doesn't define the asu. If these boundaries were combined with the masked_asu method above we'd get contiguous asu for many space groups, but rather not for all. I'd need to try it out to know how it'd work. Cctbx gives precise definitions in the asu_gallery, but they are more complex and not compatible with ccp4 boundaries. Actually syminfo.lib has 3 different definitions of asu boundaries (ccp4, zero and nonz), but I think none of them is compatible with the cctbx/ITA definitions.

**Comment by wojdyr** [comment]
I've been wondering what's more useful:
(1) ASU defined as *cuts* in the [asu_gallery](http://cci.lbl.gov/asu_gallery/), ACA and the 2011 paper "Exact direct-space asymmetric units for the 230 crystallographic space groups", or
(2) asu bricks. Brick is a parallelepiped that contains an asu (it contains more than one asu if a brick-shaped asu is not possible).

(1) would require exporting the list of cuts for each space group (reference settings only) from cctbx, and implementing other things, such as applying change-of-basis to the cuts.
(2) can be done in many ways.
In clipper it's calculated on the fly (using space group 230 as an example):
```
>>> import clipper
>>> sg = clipper.Spacegroup(clipper.Spgr_descr(230))
>>> sg.asu_min().format()
'uvw = (   -0.0001,   -0.0001,   -0.0001)'
>>> sg.asu_max().format()
'uvw = (    0.4999,    0.1251,    0.2501)'
```
Cctbx has class [brick](http://cctbx.sourceforge.net/current/c_plus_plus/classcctbx_1_1sgtbx_1_1brick.html). As the docs say, bricks are tabulated for 530+223 settings.  Bricks were computed with sginfo2 (the library written by RWGK between sginfo and sglite and never released). The problem with optimal bricks is that if they are to be tabulated, it's not sufficient to tabulate them for reference settings,  they need to be tabulated for all settings.
Here is how to use brick in cctbx:

```
>>> from cctbx import sgtbx
>>> sg = sgtbx.space_group('-I 4bd 2c 3')  # Hall symbol for SG 230
>>> sg_info = sgtbx.space_group_info(group=sg)
>>> print(sg_info.brick())
0<=x<=1/8; -1/8<=y<=0; 1/8<z<7/8
```
And we can also get bounds of the ASU, but in some cases this may be an oversized brick.
```
>>> asu = sg_info.direct_space_asu()
>>> asu.box_min()
[-1/8, -1/8, 0]
>>> asu.box_max()
[1/8, 1/8, 1/4]
```

The intentional difference between Clipper and sgtbx bricks is that Clipper has lower bound always set to (0,0,0). But I think even with this constraint for some space groups Clipper bricks are not the smallest choice. For example for SG 176 `P 63/m`:
* cctbx brick is `0<=x<=2/3; 0<=y<=1/3; 1/4<=z<=3/4`, which is 1/9 of the unit cell volume,
* cctbx asu box is [0, 0, 0] to [2/3, 2/3, 1/4] – also 1/9
* clipper asu limit is (0.6668, 0.6668, 0.3332) which gives 4/27.

Cctbx brick docs note that
> Attempts to devise an algorithm that produces bricks with contiguous asymmetric units have not been successful.

This was likely written before they assembled direct_space_asu cuts. Anyway, I've been trying to write a better brick-generating method for gemmi, but without any results so far.

(I wrote this long comment partly for myself, so I can get back to it in the future. I'll write more soon).

**Comment by CV-GPhL** [comment]
Dear Marcin,

very interesting points/discussions - thanks for looking into that
real-space ASU business! I would find it very useful to have
CCP4/TNT/XYZ bricks (a la clipper/Coot, MAPMASK/SFALL/FFT etc)
available.

Maybe there is a way of combining this with your "masking" approach -
for those cases where the brick is larger than the actual ASU: storing
a multiplicity factor for each point (maybe done via a flood-filling
algorithm to get a contiguous set marked with "1" with those set as
"2" and higher just due to the brick shape)?

Just some random thinking ...

Cheers

Clemens
-- 

*--------------------------------------------------------------
* Clemens Vonrhein, Ph.D.     vonrhein AT GlobalPhasing DOT com
* Global Phasing Ltd., Sheraton House, Castle Park 
* Cambridge CB3 0AX, UK                   www.globalphasing.com
*--------------------------------------------------------------

**Comment by wojdyr** [comment]
Clemens: one way of having CCP4 bricks would be to parse syminfo.lib file. But this would be duplicating of what libccp4 is doing. I see that TNT bricks are documented here: https://www.uoxray.uoregon.edu/tnt/manual/node111.html
What would it be useful for?

I wrote a simple brute-force function to find an asu brick and added it to the output of gemmi-sg:
```
$ gemmi sg 'P 3' | grep Direct
Direct space ASU brick: 0<=x<=2/3; 0<=y<=2/3; 0<=z<1
```
I want to test it more, then I'll make it work with Grid, add documentation, etc.

**Comment by CV-GPhL** [comment]
Hi Marcin,

On Tue, Jun 14, 2022 at 10:10:01AM -0700, Marcin Wojdyr wrote:
> Clemens: one way of having CCP4 bricks would be to parse syminfo.lib
> file. But this would be duplicating of what libccp4 is doing.

Correct.

For certain tasks/programs (MAPMASK, MAPROT, FFT, SFALL, DM, SOLOMON,
etc) one needs e.g. CCP4 map files in the exact CCP4 asymmetric unit
as expected by those programs and/or the CCP4 library. So /if/ one
would want to use Gemmi for some real-space/map related tasks and then
(after writing a CCP4 map) move to other systems/programs, having that
functionality would be very useful.

An alternative would be to always write a full unit cell and then use
e.g. MAPMASK to get to the CCP4 asymmetric unit.

> I see that TNT bricks are documented here: https://www.uoxray.uoregon.edu/tnt/manual/node111.html
> What would it be useful for?

Probably not much - but if there was a mechanism to create grids in
e.g. CCP4 asymmetric unit definitions (via some lookup table) it might
be relatively easy to do the same for other systems (TNT or CCTBX or
Clipper or whatever).

> I wrote a simple brute-force function to find an asu brick and added it to the output of gemmi-sg:
> ```
> $ gemmi sg 'P 3' | grep Direct
> Direct space ASU brick: 0<=x<=2/3; 0<=y<=2/3; 0<=z<1
> ```
> I want to test it more, then I'll make it work with Grid, add documentation, etc.

Are these then coming out as a known system (like CCP4 asymmetric
units) or something new?

Cheers

Clemens

**Comment by wojdyr** [comment]
I wrapped it up and added docs:
https://gemmi.readthedocs.io/en/latest/symmetry.html#direct-space

Asu bricks from gemmi and asu bricks from ccp4 syminfo.lib, clipper and cctbx – they are all different. In general, it shouldn't matter. As for CCP4 programs that require specific ASU, yesterday I read [Ian's post](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2206&L=CCP4BB&O=D&P=72325) that axis order also matters, so IIUC it wouldn't work anyway. Or perhaps a map for the whole unit cell will work. I don't know.

Here is a python script that I used to visualize the ASU obtained from `masked_asu()`:

```py
import sys
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import gemmi

sg = gemmi.SpaceGroup(sys.argv[1])
grid = gemmi.FloatGrid()
grid.spacegroup = sg
grid.set_size(24, 24, 24)
asu = grid.masked_asu()

fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection='3d')

xyz = np.array([idx for idx, m in np.ndenumerate(asu.mask_array) if m == 0])
x, y, z = xyz.T
ax.scatter3D(x, y, z, color='red', s=3)
ax.set_title(sg.xhm(), pad=20, size=15)
ax.set_xlim(0, 25)
ax.set_ylim(0, 25)
ax.set_zlim(0, 25)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.show()
```

The result is inside the brick, but it may still be not contiguous. For example:
![P6](https://user-images.githubusercontent.com/491873/175336060-166a0cff-490a-464b-ad93-e3bdaffee6f2.png)
![P4332](https://user-images.githubusercontent.com/491873/175335025-6acc7c26-e276-4474-a93b-20f166821414.png)
