### ISSUE TITLE
International table number and settings in Gemmi

### ISSUE THREAD

**Issue by geoffreyweal** [project-gemmi/gemmi#217]
Dear Gemmi Creators

I have been using your software to obtain the symmetry groups for all spacegroups, including those with additional settings. It has been fantastic to use!

I was wondering if it would be possible to include the following in your program:

1. Would it be possible to include a variable in Gemmi that lists all the spacegroups included in Gemmi, in order of their international table number and setting.
2. Would it be possible to include as input variables to the SpaceGroup class the international table number and setting for the spacegroup you would like to use.

Thanks

Geoffrey

**Comment by wojdyr** [comment]
Dear Geoffrey,
I don't understand your requests. Do you work with the command-line program or the library?
What do you mean by "the international table number"?

**Comment by geoffreyweal** [comment]
Hey Marcin

I am working with the library in python. For some reason I can not get the command-line program to work when I install it with pip,. I am currently looking into what is going on here, as it is probably a problem with my computer. 

Apologies I am new to crystallography and still getting use to all the terms. I mean the number given to the spacegroup (from 1 to 230), and the ITA setting (https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-def-ita_settings#:~:text=The%20option%20'ITA%20Settings'%20gives,%2C%20referred%20to%20as%20ITA)). 

Currently if I want to look at spacegroup "P c a b", I can look it up in gemmi by writing in python:

```
from gemmi import SpaceGroup
spacegroup = SpaceGroup('P c a b')
```

For what I am doing it would also be useful to be able to access the 'P c a b' using the spacegroup number and setting. For example:

```
from gemmi import SpaceGroup
spacegroup = SpaceGroup(number=61, setting=2)
```

It would also be useful to have a way to get a list of the spacegroup available in gemmi from the python library. For example:

```
spacegroup_names = {(1,1): 'P 1', (1, 2): 'A 1', (1, 3): 'B 1', ...}
```
Where the dictionary is given by 

```
spacegroup_names[(number, setting)] = extended_Hermann-Mauguin_name
```

Thanks!

**Comment by wojdyr** [comment]
pip installs only python extension. The program is available in packages from conda-forge and in a few other places: https://gemmi.readthedocs.io/en/latest/install.html#program

You access spacegroup by number:

    gemmi.SpaceGroup(61)

To get all settings for given space group you can iterate `spacegroup_table()`:

    >>> [s.xhm() for s in gemmi.spacegroup_table() if s.number == 31]
    ['P m n 21', 'P n m 21', 'P 21 m n', 'P 21 n m', 'P n 21 m', 'P m 21 n']

Gemmi doesn't have the list of settings from ITA, but it has all the settings from ITB (`gemmi.spacegroup_table_itb()`).
The full gemmi table (the one without `_itb`) starts with ITB settings (the first 530 items) and then adds some more. The ITB list is the same as in [SgInfo](http://cci.lbl.gov/sginfo/) and haven't changed since the 1990's. My understanding is that it contains all the settings from older editions of ITA, but not all from the most recent ITA edition.

**Comment by geoffreyweal** [comment]
Hello Marcin

This is perfect! Thanks for this, I didn't realise this method was available, but this is exactly what I was looking for. 

Thanks heaps for this information! Really appreciate it!

Kindest Regards

Geoffrey
