### ISSUE TITLE
PDB SEQRES conversion from MMCIF bug

### ISSUE THREAD

**Issue by jsoerensen** [project-gemmi/gemmi#22]
Getting the "PDB" header (make_pdb_headers) from 6Y2E doesn't work because the length of the chain ID is longer than a single character. I suspect the below is the problem:
https://github.com/project-gemmi/gemmi/blob/d59ef39d87dc38c6867a8c5313a621a87955902b/include/gemmi/to_pdb.hpp#L476
The lines of the header are not as expected. The SEQRES is just one big "line".
line: SEQRES   1AAA  306 SER GLY PHE ARG LYS MET ALA PHE PRO SER GLY LYS VAL           SEQRES   2AAA  306 GLU GLY CYS MET VAL 
...

I see a similar problem with HELIX/SHEET.
I think the real problem here is that the multi-character chain IDs (AAA, BBB), cause incompatibility with the PDB spec and thus these sections.
At minimum perhaps detect the use of multi-character chain IDs and perhaps just don't write these sections.

**Comment by wojdyr** [comment]
yes, that's a good point.
I added a check for long chain names to functions that output pdb file or pdb header.

I was told about this problem before, but at that time a colleague spotted it when using gemmi-convert, so I added an error message in gemmi-convert and also option `--shorten` to automatically shorten the chain names, and I didn't think about addressing it in other places.

**Comment by jsoerensen** [comment]
Thanks for the quick fix. The shorten feature would be nice for this conversion also, but is much less trivial, so the "don't write if" is a great fix.

**Comment by tinchogb** [comment]
Hello @wojdyr ,
I got a similar result using *write_pdb()* from **gemmi** python library on **[6n1d.cif](https://www.rcsb.org/structure/6N1D)**.
```
RuntimeError: long chain name: A23S
```
Seeing this issue and **gemmi convert** code I believe that **--shorten** option is missing in **write_pdb() options** and could be a good one to handle large structures convertions.\
Looking wwPDB website, I found this report: https://www.wwpdb.org/deposition/preparing-pdbx-mmcif-files .Textual they said that *"it is advisable, due to current limitations of **pdb_extract** and some visualization tools, to limit chain IDs to one or two characters."*. I didn't know that.

Just for curiosity, you know if exist any chain ID bigger than 4 character in whole wwPDB...?

**Comment by wojdyr** [comment]
ok, since it's becoming a popular request I added function shorten_chain_names()
https://gemmi.readthedocs.io/en/latest/mol.html#common-operations

**Comment by tinchogb** [comment]
Great @wojdyr, thank you for that improvement !
