### ISSUE TITLE
Provide type information for Python

### ISSUE THREAD

**Issue by eggplants** [project-gemmi/gemmi#249]
We need gemmi type hints to check codes with mypy.

It is maybe necessary to write `*.pyi` for each modules and include `py.typed` file to package data.

Spec: https://peps.python.org/pep-0561/

**Comment by eggplants** [comment]
I have created stub-only package for gemmi.
https://github.com/eggplants/gemmi-stubs

After replacing all `typing.Any` with certain types and adding proper tests, I'll send PR to this repo.

**Comment by wojdyr** [comment]
It could be useful for many gemmi users. I don't have experience with typing info, because I've been writing mostly C++ in recent years, but I like the idea.
The only concern is that we won't remember to update pyi every time something is added or changed.
Is there a way to check what is missing in pyi?

**Comment by wojdyr** [comment]
pyi files can be now generated with:

    pybind11-stubgen --enum-class-locations=Ignore:gemmi.ContactSearch --enum-class-locations=.+:gemmi gemmi

so I guess this can be used for mypy.
