### ISSUE TITLE
Gemmi failing to process large? entry 5j7v

### ISSUE THREAD

**Issue by otienoanyango** [project-gemmi/gemmi#252]
Attempt to read https://ftp.ebi.ac.uk/pub/databases/pdb/data/assemblies/mmCIF/divided/j7/5j7v-assembly1.cif.gz (930M) fails 
with the error at https://github.com/project-gemmi/gemmi/blob/master/include/gemmi/gz.hpp#L42

I uncompressed (4.7G size) and loaded the file successfully and it does take quite a bit of memory to load (~60G). 

As the method states in the comment 
```cpp
// **This function should not be relied upon.**
```
I wonder if there is a way of letting it try and failing rather than the spurious message when it can't determine the uncompressed size.

For clarity, this is so far the only file that fails to load.

**Comment by wojdyr** [comment]
I modified the check in estimate_uncompressed_size(), but there is another check that later on prevents reading files larger than 3GB. It's because handling of gzipped files is not optimized for large files. The content of the whole file is first stored in memory and then it's parsed.

That big memory usage (~60GB) probably is mostly from storing items from _atom_site CIF loop as strings. Looking on another bioassembly file from PDB, it's 26 items in row. std::string is 24 or 32 bytes (depending on compiler). This gives up to 832 bytes per atom. Additionally, the capacity of std::vector that stores these strings can be bigger than the number of strings (up to 2x bigger).

It could be optimized to handle 4.7GB coordinate files more graciously, but OTOH such files aren't common.

**Comment by otienoanyango** [comment]
Thank you for getting back and sorry for the late reply.

This will be a problem more and more because we're adding more things to mmCIF and will have more and more entries reach this limit. e.g. https://ftp.ebi.ac.uk/pub/databases/msd/updated_mmcif/divided/j3/3j3q_updated.cif.gz is 52M and https://ftp.ebi.ac.uk/pub/databases/msd/updated_mmcif/divided/j3/3j3y_updated.cif.gz is 46M and both fail with:

```
RuntimeError: Cannot determine uncompressed size of /nfs/production/gerard/pdbe/release/data/entry/j3/3j3q/sifts/3j3q_sifts_only.cif.gz
Would it be 1713 -> 0 bytes?
```

I would definitely appreciate the optimization.

**Comment by wojdyr** [comment]
The new things that were recently added **for each atom** are redundant. Why are they added?
There has been too much redundancy in the atom_site table for decades (2x atom name, 2x residue name). It'd be better to remove redundant items rather than add more of them.
Actually I already wrote it on ccp4bb when the NextGen archive was announced, so I'll copy and paste that email here.

----

Dear all,

I looked at the atom table (atom_site) in the NextGen archive. It has 5 new columns: pdbx_label_index (another sequence ID) and four columns for SIFTS mapping at atom level.
I used SIFTS in the past and having it in the coordinate file can simplify things. But as was stated in the announcement, the mapping is provided at many levels:

> Sequence mappings are provided in _pdbx_sifts_unp_segments and _pdbx_sifts_xref_db_segments categories for each segment, _pdbx_sifts_xref_db at residue level, and _atom_site at atom level.

I wonder, wouldn't it be sufficient to provide the mapping at the residue level? Repeating it for every atom actually makes working with the files harder.

For two reasons.

One is that additional identifiers will be confusing. IMO it's the main problem with mmCIF from the beginning -- too many identifiers. Every atom has two chain names, two sequence IDs, two residue names and two atom names. My guess is the IUCr committee tried to make both depositors and PDB happy. The depositor could name the chain or atom as they like, and if the PDB doesn't like the names, they can use the second set of names. (please correct me if you were there). Currently the PDB changes both sets of ids during deposition, so the "author" IDs are not really author's, but we still have these two sets. In some older entries author's chain B is PDB's chain A, and author's chain A is PDB's chain B. I think it's not controversial that having two alternative names for one thing is not particularly helpful here and, in this respect, the PDB format was designed better.
These are old problems and I don't have hope that the double naming will be dropped. But the new file looks like this:

![new-cif](https://github.com/project-gemmi/gemmi/assets/491873/eac24e6e-d064-4b04-902f-3ee15ba46004)

It has four different sequence IDs.
2 – "author" ID, the same as in the PDB
1 – "label" ID
3 – new one, apparently the same as 2 for polymers and the same as 1 for non-polymers 😳 Am I missing something?
4 – UniProt-compatible
Could we avoid it?

The second reason is bloat. I maintain code for working with CIF files (it's even used in PDBe) and just yesterday a user commented that reading 5j7v-assembly1.cif (4.7GB) requires a lot of memory. If we store each word from such a file in the simplest way in C++ (as a string), we use, say, 32 bytes per word. 5GB file with short words easily takes up 40GB of memory just for storing the words. I could work on optimizing it, but it'd help if the files were not bloated even more. The NextGen Archive has 24% more words in the atom table. All redundant.

**Comment by wojdyr** [comment]
I downloaded 3j3q_updated.cif.gz from the given link. Gemmi decompresses it on the fly (into a 300MB memory buffer) and parses it using <3GB of memory in total.

> RuntimeError: Cannot determine uncompressed size of /nfs/production/gerard/pdbe/release/data/entry/j3/3j3q/sifts/3j3q_sifts_only.cif.gz
> Would it be 1713 -> 0 bytes?

This must be a different file. The message means that the file size is less then 2kb and the size in gzip header is 0. Something went wrong.

**Comment by otienoanyango** [comment]
> This must be a different file. The message means that the file size is less then 2kb and the size in gzip header is 0. Something went wrong.
You're right. This is an internal file, and I think it may have something to do with compression since I can't unzip it. Sorry for a false alarm on a Sunday.

**Comment by otienoanyango** [comment]
I echo your sentiment about the bloatedness of the CIF file. I'll bring up the discussion
