### ISSUE TITLE
[FEATURE REQUEST] make gemmi.cif.Block object picklable

### ISSUE THREAD

**Issue by roshkjr** [project-gemmi/gemmi#258]
I am currently using gemmi.cif.Block object as an attribute of one of my python classes, and I would like to store this class using pickle. But currently I am not able to do so, because gemmi.cif.Block is not picklable.

It would be convenient if gemmi.cif.Block object can be pickled.

**Comment by wojdyr** [comment]
cif.Block is usually read from a file and/or written to a file, so I think it's rarely useful to additionally serialize it.
It could have __getstate__ that returns JSON or CIF string, but maybe it's better to save it explicitly as JSON or CIF.

**Comment by jasondbiggs** [comment]
I don't see much point in pickling a Block or Document myself, since they can just be written to JSON or CIF.  I would find it useful to pickle a `Structure` though, since there is a nonzero amount of overhead in serializing a `Structure` to mmCIF or mmJSON.

**Comment by joelb123** [comment]
Other areas of computational science have found that pickles are about the most energy-efficient serialization there is, generally about 3X higher than alternatives like Arrow (which is hundreds of times more efficient than CIF or JSON). If one accepts the caveat that the pickle will change when the library changes enough to affect the binary constructor, a `Structure` pickle can also be viewed as an extremely efficient and simple structure file format for _gemmi._

**Comment by wojdyr** [comment]
Pickling of Structure, Model, Chain, etc has been recently implemented (in git, not released yet).
It uses internally [zpp::serializer](https://github.com/eyalz800/serializer). I suppose it wouldn't be too difficult to serialize also cif.Block in the same way. But is it still needed by anyone?

**Comment by joelb123** [comment]
One very much needs a way to serialize a JSON dictionary without the high time and energy costs of writing the CIF. I would useCIF block data for this rather than using CIF-native dictionary items for several reasons,Including dictionaries of dictionaries beingsimple and standard.So yes, I would want to pickle CIF blocks,Unless you can think of a better way to pickle dictionaries in the same pickle fileSent from my iPhoneOn Sep 14, 2024, at 10:07 AM, Marcin Wojdyr ***@***.***> wrote:﻿
Pickling of Structure, Model, Chain, etc has been recently implemented (in git, not released yet).
It uses internally zpp::serializer. I suppose it wouldn't be too difficult to serialize also cif.Block in the same way. But is it still needed by anyone?

**Comment by wojdyr** [comment]
@joelb123 I don't understand your comment. Could you clarify?
For example, what do you mean by CIF-native dictionary items?

**Comment by joelb123** [comment]
My apologies for not being clear. I appreciate that you followed up.

The use case is for programs which calculate data about a structure contained in a CIF file which is to be passed along downstream; pretty much every program, in other words. Typically this has been handled by creating additional files. The problems with additional files are that they requiresadditional transfers, knowing naming conventions, and passing these along the chain. It only takes one consumer/producer breaking the chain to result in losing data and metadata., so in storing data in the file is my standard practice whenever I can.  Sometimes that has to be done in comments, but CIF provides data blocks. While CIF blocks come with the (d*mb and ugly, in my opinion) restrictions of reduced character set and 80-character line length, I can easily put encode (e.g., radix-64 with line breaks) any JSON-encoded dictionaries into legal CIF blocks in a way that others can retrieve them, complete with a (non-JSON) human-readable comment on how to decode them.

What I meant by CIF-native dictionary items is the <tag> <value> system CIF is based on. You could say that I could just as easily define my own tags and put data into them, but that runs into much more ugliness than putting them in data blocks because of the 2048-byte limit for CIF strings.

If you can think of an alternative to using CIF data blocks for storage of arbitrary user-defined data, I'd love to hear it. Personally, I think that CIF should be chucked in favor of something standard (parquet), but that's a bigger battle than I can fight right now.

**Comment by wojdyr** [comment]
We also discuss here, from time to time, how to pass additional data along with the structure. Including it in a coordinate CIF file also doesn't guarantee that it will be passed all the way down. Many programs will ignore it and not copy it to the output, and that's a valid approach. Metadata in a file that's an input to MR or refinement may originate from a different structure, so it's not clear what should be passed further down.

Regarding line length, the limit in CIF 1.1 (which I understand is the basis of mmCIF) is 2048. Additionally, many CIF parsers don't impose any limits on line length, so I wouldn't worry about it.

**Comment by wojdyr** [comment]
I just added picking of cif.Document and cif.Block.
Testing it on ~400MB components.cif, the pickle is even bigger (~500MB), but it's 3x faster to read.
```
In [8]: %timeit ccd = gemmi.cif.read('components.cif')
4.28 s ± 71.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: %time with open('ccd.pkl', 'wb') as f: pickle.dump(ccd, f)
CPU times: user 698 ms, sys: 616 ms, total: 1.31 s
Wall time: 1.43 s

In [10]: %time with open('ccd.pkl', 'rb') as f: unpickled = pickle.load(f)
CPU times: user 1.21 s, sys: 102 ms, total: 1.31 s
Wall time: 1.31 s

In [11]: %timeit with open('ccd.pkl', 'rb') as f: unpickled = pickle.load(f)
1.34 s ± 2.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
This was from GCC 14 and `-O2`.
