### ISSUE TITLE
C++ types in python docstrings

### ISSUE THREAD

**Issue by sizmailov** [project-gemmi/gemmi#280]
I used the `gemmi` library as a test binary module for the stub generator and found a few issues. The errors do not affect runtime behavior but might corrupt API generation.

```
pybind11_stubgen - [  ERROR] In gemmi : Invalid expression 'std::vector<gemmi::Topo::ResInfo, std::allocator<gemmi::Topo::ResInfo> >'
pybind11_stubgen - [  ERROR] In gemmi : Invalid expression 'std::vector<gemmi::Topo::Rule, std::allocator<gemmi::Topo::Rule> >'
pybind11_stubgen - [  ERROR] In gemmi : Invalid expression 'std::vector<gemmi::Topo::FinalChemComp, std::allocator<gemmi::Topo::FinalChemComp> >'
pybind11_stubgen - [  ERROR] In gemmi : Invalid expression 'std::vector<gemmi::Topo::Mod, std::allocator<gemmi::Topo::Mod> >'
pybind11_stubgen - [  ERROR] In gemmi : Invalid expression 'std::vector<gemmi::Topo::Link, std::allocator<gemmi::Topo::Link> >'
```

Code to reproduce:
```
pip install gemmi pybind11-stubgen==1.0.dev1
pybind11-stubgen gemmi
```

**Comment by wojdyr** [comment]
Fixed.

It's a nice project. So far I was using:

    $PYTHON -m pydoc gemmi | grep ::

to catch such issue, but it didn't caught everything, because pydoc doesn't display everything.

I suppose it solves #249 (@eggplants)?

Could it have an option to check for errors only, without generating the stubs?

Did you look into [nanobind][1]? I'm thinking about migrating to it at some point.

[1]: https://nanobind.readthedocs.io/en/latest/why.html

**Comment by sizmailov** [comment]
I added `--dry-run` option to skip the writing stubs 
```
pybind11-stubgen --dry-run --exit-code gemmi
# `--exit-code makes it return a non-zero exit code in case of errors
```

Unfortunately, I didn't have a chance to have a closer look at nanonbind.
