### ISSUE TITLE
Publishing PDB REMARK X's

### ISSUE THREAD

**Issue by rimmartin** [project-gemmi/gemmi#287]
Hi,

What are your thoughts on pdb REMARK's?  Particularly REMARK 3?  Just looking at https://www.wwpdb.org/documentation/file-format-content/format33/remark3.html each tool seem to do their own thing.

Currently any raw remarks turns off REMARK 2 & 350?

I populated the RefinementInfo and do see cif output has the refinement tags.

Some of our users aren't yet thinking about going to cif so I'm being asked about REMARK 3 particularly

**Comment by wojdyr** [comment]
I'm familiar with REMARK 3. Yes, it's apparently not standardized. Gemmi can read it (remarks.hpp) to the extent that was necessary to convert PDB files from BUSTER to mmCIF.

> Currently any raw remarks turns off REMARK 2 & 350?

Yes. If there are raw_remarks, they are written without inspecting what's inside. Otherwise, some new remarks are generated (the ones that you mentioned). I didn't try to combine these two options.

Why do your users ask about REMARK 3? Do you write an MX refinement program?

**Comment by rimmartin** [comment]
Yes.  Besides running as optional qm/oniom gradient engine under BUSTER and Phenix we also refine directly with density input

**Comment by wojdyr** [comment]
Do you know what your users want to have in REMARK 3?
They might need only a few numbers from it. I imagine that they need it for in-house pipelines, because the deposition to the PDB requires mmCIF.
You could add these remark records in `write_remarks()` in src/to_pdb.cpp.
Or just wait a few months. The PDB will start assigning 5-letter-codes for new ligands soon. This may push some orgs to move to mmCIFs.

**Comment by rimmartin** [comment]
That's a thought.  Will depend on how much pressure comes. Our direct refinement is real space semi-empirical qm compatible with CryoEM input so not as much to fill in REMARK 3(which looks grievously unspec'ed to me) at this point.

Some folks wouldn't know how to live without saying PeeDeeBee's real fast a few times a day:-) Have a good Thanksgiving
