### ISSUE TITLE
Gemmi fails to set the true grid spacing if origin is not (0, 0 ,0) for a CCP4 map

### ISSUE THREAD

**Issue by jrobsontull** [project-gemmi/gemmi#288]
We're using Gemmi to read cryo-EM maps using the Python API `gemmi.read_ccp4_map()`.

When reading maps where the origin is not `(0, 0, 0)` then the resulting `gemmi.Ccp4Map.grid` does not correctly set the spacing and it defaults to `(0, 0, 0)`. Other tools such as ChimeraX can correctly interpret the grid spacing despite the origin not being `(0, 0, 0)`. Our maps don't necessarily have a 0 origin if we have translated them in other tools e.g. for map-to-map fitting.

Is this behaviour expected and what should we be doing differently?

**Comment by wojdyr** [comment]
yes, you wrote clearly that it's about spacing, but somehow I didn't register it.
It's fixed now.

If ORIGIN was non-zero, the map was not fully set up because it wasn't obvious to me what would work, and what wouldn't with non-zero origin. I just changed it, now the ORIGIN is simply ignored. But quite possibly, not all functions work sensibly with a shifted origin.

I added a note about it to docs:
> The MRC variant of the format contains the ORIGIN header records (words 50-52)
> that specify the location (in Angstroms) of a subvolume taken
> from a larger volume. Gemmi functions ignore this header because our focus
> was on crystallographic applications. Using it is up for discussion.

**Comment by jrobsontull** [comment]
Thanks for this! But makes sense that this may impact other functions and adding a note about this in the docs seems the best approach for now.
