### ISSUE TITLE
Creating a structure from list of residues and their coordinates

### ISSUE THREAD

**Issue by marinegor** [project-gemmi/gemmi#315]
Hi everyone, sorry to bother you again -- I wonder how I could actually write an mmcif file, given e.g. a list of atom names + residue names + coordinates?

I'm searching for an interface like:

```python
import gemmi
import numpy as np

my_object = ...
np_structure: np.ndarray = np.array([(atomname, resname, *coords) for atomname, resname, coords in my_object])
gemmi_structure = gemmi.Structure.from_numpy(np_structure)  # this is the method that I'm struggling to find
gemmi_structure.write_mmcif(...)  # and this as well
```

could you point me to the right direction please?

**Comment by wojdyr** [comment]
mmCIF files tend to have more information, although in principle write only a subset of it. I suppose in this case the occupancy is 1.0 and there are no alternative conformations, and you want a single chain. But you still need to assign the chain name, B-factors and sequence IDs (other programs will expect it). Sequence IDs can't be determined from the resname alone, because consecutive residues can have the same resname. The elements, if you want to have them in a file, would need to be looked up in CCD.

There is no similar function. It's only possible to do it by constructing all the objects (chains,residues,atoms) one by one. Or by constructing directly a CIF Document using functions such as [set_mmcif_category][1].

[1]: https://gemmi.readthedocs.io/en/stable/cif.html#set-mmcif-category

**Comment by marinegor** [comment]
>There is no similar function. It's only possible to do it by constructing all the objects (chains,residues,atoms) one by one. 

Oh, I see, thanks! I guess I should also initialize all sub-attributes by hand, e.g. `gemmi.Position`, `gemmi.Element`, etc.
