### ISSUE TITLE
Consistency of call signatures in gemmi.Op and vectorized apply_to_hkl() and phase_shift()

### ISSUE THREAD

**Issue by JBGreisman** [project-gemmi/gemmi#8]
Hi -- 

I have been writing a package for representing and manipulating reflection tables in pandas dataframes, and have been using `gemmi` as a backend for some of the features related to IO of MTZ files and space group symmetry operations. 

Currently, `gemmi.Op.apply_to_hkl()` takes HKL indices as a list/tuple; however, `gemmi.Op.phase_shift()` takes HKL indices as 3 subsequent `int` arguments. Should these two call signatures be made consistent by changing `phase_shift()` to take HKL indices as a list/tuple?

i.e. changing this:
`phase_shift(self: gemmi.Op, h: int, k: int, l: int) -> float`

to:
`phase_shift(self: gemmi.Op, hkl: List[int[3]]) -> float`

On a related note, it seems like it would be useful to vectorize these operations to work on lists/np.ndarrays of HKL indices. While it is easy to write a for-loop to handle it, it seems like a common enough use case that it might warrant overloading the functions to also handle call signatures like:

`apply_to_hkl(self: gemmi.Op, hkl: List[ List[ int[3] ] ]) -> List[ List[ int[3] ] ]`
and
`phase_shift(self: gemmi.Op, hkl: List[ List[ int[3] ] ]) -> List[ float ]`

These are really more of feature requests than "issues," but I look forward to your thoughts--

Thanks,
Jack

**Comment by wojdyr** [comment]
Hi Jack,

regarding `phase_shift()` -- thanks for pointing it out, I've changed it as you proposed.

regarding vectorization in Python - I was considering vectorization of some functions, because after reading pybind11 it seems like an easy thing to do:
https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#vectorizing-functions
But I haven't experimented with it yet. 
I don't know if working with reflection data in numpy arrays will be a common use case :-)
You are probably the first person doing this, these functions are not even documented yet.
But on the other hand, these functions are good candidates for vectorization.
In your use case, are these the only functions that would benefit from vectorization?

**Comment by JBGreisman** [comment]
Hi Marcin,

Thanks for taking care of this so quickly.

Working with reflection data in numpy arrays may not be a common use case yet, but I hope it will be some day! In general, I think any function that maps HKL indices in a pairwise manner to something (either other HKLs or floats) ought to be a good candidate for vectorization. I've been using 3 functions that meet that criteria:
- `Op.apply_to_hkl()`
- `Op.phase_shift()`
- `UnitCell.calculate_d()`

Looking at the call signature for `UnitCell.calculate_d()`,  it takes 3 sequential `float` arguments:

`calculate_d(self: gemmi.UnitCell, hk: float, k: float, l: float) -> float`

Please let me know if you think it also makes sense to change the signature of this one as well:

`calculate_d(self: gemmi.UnitCell, hkl: List[float[3]]) -> float`

If it ends up being straightforward to vectorize these functions (the pybind11 documentation certainly makes it seem like close to a one-liner), I think these changes in call signatures will make the syntax for these functions most consistent.

**Comment by wojdyr** [comment]
Hi Jack,
I changed calculate_d and calculate_1_d2, but vectorization is not that simple.
It would be simple if the arguments were single numbers (i.e. h, k and l separately, not [h,k,l]), and if the result would also be a single number. So apply_to_hkl() is particularly problematic because of the return value.
Maybe if hkl was passed around in some structured numpy datatype it would work, but I'm not sure.

**Comment by JBGreisman** [comment]
Got it -- thanks for the changes in call signatures.

For now, I have vectorized versions of  in my code that use attributes of `gemmi.Op` and `numpy` functions. This is definitely an example of "passing around as structured numpy datatypes", though as you mentioned. 

for example:
```python
def apply_to_hkl(H, op):
    """
    H : np.ndarray
        (n x 3) numpy array of Miller indices
    op : gemmi.Op
        symmetry operation
    """
    return np.floor_divide(np.matmul(H, op.rot), op.DEN)
```

**Comment by wojdyr** [comment]
Neat! That's probably the best solution.
Let me know when your package is publicly available.

**Comment by JBGreisman** [comment]
I'm going to close this issue -- it may be worth revisiting vectorization in the future, but I will keep it in our package for now. 

I will be sure to let you know when we release our code!
